title: 12 janvier 2010
author: Newton02
email: formation90.github@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  then I still looked for how to program without using this platform.
  Actually, I realize I can do better if I learn how to use it that why I choose to spend my time in learning how to use Github.
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
